modLoader="javafml"
loaderVersion="[47,)"
license="LGPLv3"
logoFile="logo.png"

[[mods]]
modId="ctnhchangelog"
version="${mod_version}"
displayName="CTNH Changelog"
logoFile="ctnhchangelog.png"
credits="CTNH Team"
authors="CTNH Team"
description='''
Changelog viewer for Create: New Horizon modpack.
'''
[[dependencies.ctnhchangelog]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="CLIENT"

[[dependencies.ctnhchangelog]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="CLIENT"

[[mixins]]
config="ctnhchangelog.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"